# Generated by Django 3.0.2 on 2020-11-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201108_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dept',
            field=models.CharField(blank=True, default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='roll',
            field=models.IntegerField(blank=True, default=17),
        ),
    ]
