# Generated by Django 3.0.2 on 2020-11-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201108_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roll',
        ),
    ]
