# Generated by Django 3.0.2 on 2020-11-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201108_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ut1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='ut2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='ut3',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
