# Generated by Django 3.0.2 on 2020-11-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201108_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ut12',
            field=models.ImageField(blank=True, upload_to='plots'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ut13',
            field=models.ImageField(blank=True, upload_to='plots'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ut23',
            field=models.ImageField(blank=True, upload_to='plots'),
        ),
    ]
