# Generated by Django 3.0.2 on 2020-11-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201109_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ut1p',
            field=models.ImageField(blank=True, upload_to='plots'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ut2p',
            field=models.ImageField(blank=True, upload_to='plots'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ut3p',
            field=models.ImageField(blank=True, upload_to='plots'),
        ),
    ]
